// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgIpIOmmoPk6ij9HduK6Jb8b67naPeBDw',
    appId: '1:684595439219:web:fea26f09bbbd1d65a22c06',
    messagingSenderId: '684595439219',
    projectId: 'droswy-driving',
    authDomain: 'droswy-driving.firebaseapp.com',
    storageBucket: 'droswy-driving.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDKymPDWjAKmmFmnkyuSwKQS0wkxzQYOY',
    appId: '1:684595439219:android:f81522a67ec65c6ca22c06',
    messagingSenderId: '684595439219',
    projectId: 'droswy-driving',
    storageBucket: 'droswy-driving.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSitbQ0gR7X3VPIrF0NzvmLR7Eui8JyA0',
    appId: '1:684595439219:ios:9818523349e0461fa22c06',
    messagingSenderId: '684595439219',
    projectId: 'droswy-driving',
    storageBucket: 'droswy-driving.firebasestorage.app',
    iosBundleId: 'com.example.drowsinessGuide',
  );
}
